---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: test
  become: true
  tasks:

  - name: Install Apache2 and php Support packages
    tags: apache,apache2,Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Start apache2
    tags: apache,apache2
    service:
      name: apache2
      state: started
