---

- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      update_only: yes
      update_cache: yes

- hosts: test
  become: true
  tasks:

  - name: Install Apache2 and php Support packages
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
